# Set shell to TARGET_SHELL
set-option -g default-shell $TARGET_SHELL

# Override prefix key
set -g prefix C-x
unbind-key C-b
bind-key C-x send-prefix

# Paste without copy mode
bind-key -n C-] paste-buffer

# Override copy mode k
unbind-key -T prefix [
bind-key -T prefix c copy-mode

# Bind modeless search up key
unbind-key -T copy-mode C-s
bind-key -n C-e copy-mode \; command-prompt -i -I "#{pane_search_string}" -T search -p "(search up)" { send-keys -X search-backward-incremental "%%" }

# Define custom clipboard-via-VSCode popluation command
set -s command-alias[6] "paste=save-buffer /tmp/clipboard"
bind-key v paste \; run-shell $HOME/.code_dump_to_clipboard
